### ISSUE TITLE
limit bandwith per client

### ISSUE THREAD

**Issue by moofkit** [hkbakke/tc-gen#3]
Hi, @hkbakke ! 
Thanks for wrapper that makes easier for setup traffic shaping.
Is it possible to setup limiting also per connection (i.e. ip client) as described in this stack [question](https://serverfault.com/questions/174010/limit-network-bandwith-for-an-ip)?
We have limiting speed per interface, but it is not exactly the same.

**Comment by hkbakke** [comment]
Hi

It is of course possible, but I don't see how I could bake that into tc-gen and still keep it so simple as it is today. 

I would also like to note that tc-gen makes use of fq_codel, of which a major point is to be able to efficiently allow full usage of the link but still allow fair distribution an keepl low latency for many streams without having to create complex priority multiqueue setups. 

I realize that there are some valid usecases for restricting bandwith per user, regardless of how good fq_codel is to handle bandwithdistribution in realtime, but special usecases is not really within the scope of tc-gen as it is today.

**Comment by moofkit** [comment]
@hkbakke thx anyway! Complete this task with custom tc configuration!
